### ISSUE TITLE
Modify footer to take value of source repo from /api/systemInfo instead of being hardcoded

### ISSUE THREAD

**Issue by nathanmathew02** [ucsb-cs156-f22/f22-7pm-happycows#7] opened 2022-11-17 08:37 UTC
The footer has a link to the source repo:

![Image](https://user-images.githubusercontent.com/73052468/202397181-71b55a7b-e8ba-4c83-ae98-8d9bb72d4971.png)

The word GitHub links currently to: https://github.com/ucsb-cs156-s22/s22-6pm-happycows

Another issue is handling moving this value to /api/systemInfo. Change the footer component so that it gets the value of the URL for the source repo from /api/systeminfo

The navbar also uses systemInfo so you can see how it is handled there.

Be sure to modify tests, and storybook entries accordingly.

Also modify the fixtures for systemInfo to contain the new example values for sourceRepo

**Comment by ethwu** [comment] 2022-11-18 01:19
Is this a duplicate of #1 ?

**Closed** 2022-11-20 17:32 UTC
